name: Generate Radial Language Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily

permissions:
  contents: write

jobs:
  generate-radials:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: pip install matplotlib requests

      - name: Remove old charts (ignore if missing)
        run: |
          git rm -f --ignore-unmatch .github/radial-c.svg .github/radial-cpp.svg || true

      - name: Generate radial charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/generate_radials.py

      - name: Commit and push charts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/radial-c.svg .github/radial-cpp.svg || true
          git commit -m "chore: update C & C++ radial charts [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: List generated files
        run: ls -la .github/radial-*.svg || echo "No radial charts generated"
