name: GitHub Metrics

on:
  # Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - uses: actions/checkout@v3

      # Generate C-only stats
      - name: Generate C Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-c.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_filter: c
          plugin_languages_limit: 10
          plugin_languages_categories: programming
          plugin_languages_analysis_timeout: 30
          plugin_languages_other: false

      # Generate C++-only stats
      - name: Generate C++ Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-cpp.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_filter: cpp
          plugin_languages_limit: 10
          plugin_languages_categories: programming
          plugin_languages_analysis_timeout: 30
          plugin_languages_other: false
