name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Run daily at midnight UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow writing files back
    steps:
      - uses: actions/checkout@v3

      # Generate C metrics
      - name: Generate C Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-c.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_filter: c
          plugin_languages_limit: 10
          plugin_languages_categories: programming

      # Generate C++ metrics
      - name: Generate C++ Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-cpp.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_filter: cpp
          plugin_languages_limit: 10
          plugin_languages_categories: programming

      # Commit and push results
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics-c.svg metrics-cpp.svg
          git commit -m "chore: update metrics charts [skip ci]" || echo "No changes to commit"
          git push
        env:
          # This gives Git push authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
